### ISSUE TITLE
MetFrag doens't process

### ISSUE THREAD

**Issue by DanielStay** [c-ruttkies/MetFrag#5]
Hey,

I've been trying to use MetFrag for several days but unfortunately it doesn't process the candidates.

Cheers

Daniel

**Comment by c-ruttkies** [comment]
Hi Daniel,
we had some problems on our compute server. Should be fixed now.
Thanks,
Christoph

**Comment by DanielStay** [comment]
Hi Christoph,

thanks for the quick update. However, the processing is still not working. I'll try again in a few hours.

Thanks 

Daniel

**Comment by c-ruttkies** [comment]
Are you relating to the older (msbi.ipb-halle.de/MetFrag) or newer version (msbi.ipb-halle.de/MetFragBeta) ?

**Comment by DanielStay** [comment]
I'm relating to the newer version (msbi.ipb-halle.de/MetFragBeta). I just checked again and it's working now.

Thanks
